/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import conexoes.ConexaoMySql;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author ALEX
 */
public class ViewSplash extends javax.swing.JFrame {

    BufferedImage imagenFundo;
//istacia a classe de conexão
    ConexaoMySql con = new ConexaoMySql();

    /**
     * Creates new form TelaSplas
     */
    public ViewSplash() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Como alterar o ícone default do java JFrame Swing?
        URL url = this.getClass().getResource("/Imagens/Usuario_pequeno.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        repaint();
        //seta o titulo da janela
        setTitle("Splash");

        new Thread() {
            public void run() {
                for (int i = 0; i < 101; i++) {
                    try {
                        sleep(60);
                        jProgressBar1.setValue(i);
                        jLabelDecorido.setText(Integer.toString(i) + "%");
                        if (jLabelDecorido.getText().equals("20%")) {
                            lblStatus.setText("Carregando Modulos do sistema");
                        } else if (jLabelDecorido.getText().equals("40%")) {
                            lblStatus.setText("Buscando Fontes");

                        } else if (jLabelDecorido.getText().equals("50%")) {
                            lblStatus.setText("Carregando Modulos de configuração");

                        } else if (jLabelDecorido.getText().equals("60%")) {
                            lblStatus.setText("Validando Criptografia");

                        } else if (jLabelDecorido.getText().equals("85%")) {
                            lblStatus.setText("Conexão verificada");
                        }
                    } catch (InterruptedException ex) {
                        System.out.println("Erro: " + ex);
                    }
                }
                try {
                    con.conectar();
                    if (con.isStatus()) {
                        lblStatus.setText("Conexão verificada");
                        ViewPrincipal viewPrincipal = new ViewPrincipal();
                        viewPrincipal.setVisible(true);
                        dispose();
                    } else {
                        lblStatus.setText("Error na conexão verifique a cofiguração da ferramenta de conexão");
//                        ViewConexao viewConexao = new ViewConexao();
//                        viewConexao.setVisible(true);
                        //dispose();
                    }
                    //fecha a conexão
                    con.fecharConexao();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "ERROR: "+e);
                    dispose();
                }
            }

        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCPanelSplash = new com.bolivia.panel.JCPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDecorido = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Splash");
        setBackground(new java.awt.Color(0, 51, 204));
        setUndecorated(true);
        setOpacity(0.9F);

        jCPanelSplash.setFirstColor(new java.awt.Color(240, 240, 240));
        jCPanelSplash.setIconLogo(new javax.swing.ImageIcon(getClass().getResource("/Imagens/scorpio-2878338_640_1.png"))); // NOI18N
        jCPanelSplash.setLocationLogo(new java.awt.Point(10, 10));
        jCPanelSplash.setSecondColor(new java.awt.Color(153, 153, 153));
        jCPanelSplash.setSideHexagon(20);
        jCPanelSplash.setUseMode(com.bolivia.panel.USEMODE.HEXAGON);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Por: Luiz Lauro Silva Gonçalves");

        jLabelDecorido.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabelDecorido.setForeground(new java.awt.Color(0, 0, 204));
        jLabelDecorido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDecorido.setText("99%");

        lblStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblStatus.setText("Carregando...");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 55)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SGBD");

        jProgressBar1.setForeground(new java.awt.Color(238, 112, 82));
        jProgressBar1.setRequestFocusEnabled(false);
        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Analise em Curso");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Todos os direitos reservados");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("1.0");

        javax.swing.GroupLayout jCPanelSplashLayout = new javax.swing.GroupLayout(jCPanelSplash);
        jCPanelSplash.setLayout(jCPanelSplashLayout);
        jCPanelSplashLayout.setHorizontalGroup(
            jCPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCPanelSplashLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jCPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCPanelSplashLayout.createSequentialGroup()
                        .addGroup(jCPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDecorido, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jCPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jCPanelSplashLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(jCPanelSplashLayout.createSequentialGroup()
                .addContainerGap(388, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jCPanelSplashLayout.setVerticalGroup(
            jCPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCPanelSplashLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jCPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabelDecorido)
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCPanelSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCPanelSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(748, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSplash.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSplash.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSplash.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSplash.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSplash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bolivia.panel.JCPanel jCPanelSplash;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDecorido;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
